name: Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write
  id-token: write

jobs:
  msdo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Microsoft Security DevOps Scan
      - name: Run Microsoft Security DevOps Scan
        uses: microsoft/security-devops-action@v1
        with:
          categories: 'IaC,Secrets'

      # Step 3: List MSDO results
      - name: List MSDO results
        run: ls -R ${{ github.workspace }}/.gdn || echo "No results found"

      # Step 4: Install required tools for PDF conversion
      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf jq

      # Step 5: Convert SARIF to TXT for readability
      - name: Convert MSDO results to TXT
        run: |
          mkdir -p ${{ github.workspace }}/.gdn/pdf
          if [ -f ${{ github.workspace }}/.gdn/msdo.sarif ]; then
            jq '.runs[].results[] | {ruleId, message: .message.text, level: .level, locations: .locations}' \
              ${{ github.workspace }}/.gdn/msdo.sarif > ${{ github.workspace }}/.gdn/pdf/msdo-results.txt
          else
            echo "No SARIF file found!" > ${{ github.workspace }}/.gdn/pdf/msdo-results.txt
          fi

      # Step 6: Convert TXT to PDF using wkhtmltopdf
      - name: Convert TXT to PDF
        run: |
          echo "<pre>$(cat ${{ github.workspace }}/.gdn/pdf/msdo-results.txt)</pre>" > ${{ github.workspace }}/.gdn/pdf/msdo-results.html
          wkhtmltopdf ${{ github.workspace }}/.gdn/pdf/msdo-results.html ${{ github.workspace }}/.gdn/pdf/msdo-results.pdf

      # Step 7: Upload PDF artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: msdo-results-pdf
          path: ${{ github.workspace }}/.gdn/pdf/msdo-results.pdf
          if-no-files-found: warn
          retention-days: 30

      # Step 8: Optional - Upload SARIF for GitHub Security (requires GHAS)
      - name: Upload SARIF results to GitHub Security
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/.gdn/msdo.sarif
          checkout_path: ${{ github.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}
